name: speechre

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8.6
  - pip=20.3.3
  - tqdm=4.49.0
  - pandas=1.2.3
  - pytorch=1.8.1
  - torchaudio=0.8.1
  - cudatoolkit=10.2.89
  - sentencepiece=0.1.91
  - editdistance=0.5.3
  - transformers=4.4.2
  - pysoundfile=0.10.3.post1
  - num2words=0.5.10
  - nltk=3.5
  - numpy=1.20.2
  - tensorboard=2.4.1

  - pip:
    - jiwer==1.3.2
    - fairscale==0.3.4
    - deepspeed==0.3.14
    - git+https://github.com/facebookresearch/wavaugment.git