# @package _group_

encoder_embed_dim: 256
encoder_ffn_embed_dim: 1024  # 256 * 4
encoder_attention_heads: 4
encoder_layers: 6

decoder_embed_dim: 256
decoder_ffn_embed_dim: 1024  # 256 * 4
decoder_attention_heads: 4
decoder_layers: 3
decoder_output_dim: 256
decoder_input_dim: 256

dropout: 0.3
attention_dropout: 0.3
activation_dropout: 0.3